#!/bin/bash

WORKDIR="./";

if [ "$#" -eq "0" ]; then
	echo "Usage : unsvn [path]"
	echo "path : working copy start point"
	exit 0
else
	WORKDIR=$1
fi

SVN_FILES=".svn"

# List
find "${WORKDIR}" -depth -name "${SVN_FILES}"

# Deletion
find "${WORKDIR}" -depth -name "${SVN_FILES}" -exec rm -Rf {} ;

