#!/bin/bash

SWITCH_SUFFIX="switched"
SWITCH_GOAL=""
SWITCH_SOURCES_LIST_D="/etc/apt/sources.list.d"
SWITCH_TEST="./test"

function _unswitch() {
	mv "$1_$SWITCH_SUFFIX" "$1"
	if [ $? -eq 0 ]; then
		echo "switched on"
	fi
}

function _switch() {
	mv "$1" "$1_$SWITCH_SUFFIX"
	if [ $? -eq 0 ]; then
		echo "switched off"
	fi
}

if [ $# -eq 0 ]; then
        echo "Usage : switch <GOAL> <ACTION>"
	echo "GOAL :"
	echo "	apt, sources.list.d :	$SWITCH_SOURCES_LIST_D"
	echo "ACTION :"
	echo "	0, off, OFF, disable :	switch off"
	echo "	1, on, ON, enable :	switch on"
        exit 0;
elif [ $# -lt 2 ]; then
	echo "At least one argument missed"
	exit 1;
fi

case "$1" in
	apt | sources.list.d)
		SWITCH_GOAL="$SWITCH_SOURCES_LIST_D"
	;;

	test)
		SWITCH_GOAL="$SWITCH_TEST"
	;;

	*)
		echo "Unknown goal"
		exit 2;
	;;
esac

case "$2" in
	1 | on | ON | en | enable)
		_unswitch "$SWITCH_GOAL"
	;;

	0 | off | OFF | dis | disable)
		_switch "$SWITCH_GOAL"
	;;

	*)
		echo "Unknown action"
		exit 3;
	;;
esac

