#!/bin/bash

source ../debmake/debmake

SRC_DIR="./src"
PKG_DIR="./pkg/deb"
DST_DIR="."
TMP_DIR="/tmp"

CONTROLE_FILE="$PKG_DIR/DEBIAN/control"

WKG_DIR=`_PrepareWorkingDirectory "$TMP_DIR" "$CONTROLE_FILE"`

_CopyContentIgnoreHidden "$PKG_DIR" "$WKG_DIR"

_CopyCreateDir "$SRC_DIR/srevert" "$WKG_DIR/usr/bin"
_CopyCreateDir "$SRC_DIR/unsvn" "$WKG_DIR/usr/bin"

_MakeDeb "$WKG_DIR" "$DST_DIR"
